;
; File generated by cc65 v 2.18 - Ubuntu 2.18-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.18-1"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_draw_rect_filled
	.import		_VGA_CFG
	.importzp	_VGA_CFG_STASH
	.import		_vga_flip
	.export		_main

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	ldx     #$00
	lda     #$00
	sta     _VGA_CFG_STASH
	ldx     #$00
	lda     #$00
	sta     _VGA_CFG
	lda     #$0A
	jsr     pusha
	lda     #$0A
	jsr     pusha
	lda     #$0A
	jsr     pusha
	lda     #$0A
	jsr     pusha
	lda     #$FF
	jsr     _draw_rect_filled
	jsr     _vga_flip
	jmp     L0010
L0010:	jmp     L0010
	rts

.endproc

